FROM nginx

RUN apt-get update && apt-get install -y vim && apt-get install -y iputils-ping 

COPY index.html /usr/share/nginx/html/index.html

WORKDIR /usr/share/nginx/html/

CMD ["nginx", "-g", "daemon off;"]